### PR TITLE
Chapt2

### PR DESCRIPTION
**Pull request by defuneste**
Chapter 2 first part plus adding packages in DESCRIPTION

### CODE REVIEW

**Review by jonthegeek — DISMISSED** [review]
Thanks!

**Comment by defuneste** [comment]
spDatalarge is big! we will see if it works thanks for checking that!

**Comment by jonthegeek** [comment]
@defuneste It built locally when I added these things to DESCRIPTION, so hopefully GHA will also be ok with it! It just might be slow, but meh, normally we aren't in a rush to get things merged!

**Review by jonthegeek — DISMISSED** [review]
Hopefully this will do it!

**Review by jonthegeek — APPROVED** [review]
Ok, hopefully THIS will do it!

**Pull request merged**
